config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", as: :log_out

  resources :sessions
  resources :users
  resources :posts

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email



 def encrypt_password
   self.password_salt = BCrypt::Engine.generate_salt
   self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
 end

 def self.authenticate(email, password)
  user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 1)
    #@posts_by_month = Post.find(:all, :order => 'created_at DESC').group_by { |post| post.created_at.strftime("%B %Y") }
  end



  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end


  def create
    @post = Post.new(post_params)
  if @post.save
    flash[:notice] = "Your post has been created"
    redirect_to @post
  end
end

  private

  def post_params
    params.require(:post).permit(:title, :text, :image)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  

  def create
    @user = User.authenticate(params[:email], params[:password])
      if @user
        flash[:notice] = "You've been logged in."
        session[:user_id] = @user.id
        redirect_to root_path
     else
        flash[:alert] = "There was a problem logging you in."
        redirect_to log_in_path
     end
  end
 

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Thanks for signing up."
      redirect_to root_url 
    else
      render "new"
    end
  end

   def new
    @user = User.new   
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def signed_in?
    !current_user.nil?
  end


  def current_user?(user)
    user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Single Digit Success</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>

  <% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
<body>
    <div id = "content">
      <div class = "container">
        <%= render 'shared/header' %>
    


    <%= yield %>

   
    </div>
  </div>
  <%= render 'shared/footer' %>
</body>
  

    





</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class = "row">
          <div class = "col-md-9">
            <h2><%= link_to post.title, post_path(post) %></h2>
            <img src="http://lorempixel.com/200/280/sports/8" id = "article-image" class="img-responsive">
            
              <p><%= post.text %></a></p>
              <i class="fa fa-comments"> comments (3)</i> <p><%= link_to "Make a Comment", post_path(post) %></p>
              <center><%= will_paginate @posts, renderer: BootstrapPagination::Rails %></center>
              <% end %>
          </div>


          <div class = "col-md-3">
            <div class = "well" id = "newsletter_well">
                <h3 id = "newsletter-title">Free Workout Program and Diet!</h3>
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                  <input type="text" class="form-control" placeholder="Enter email here">
                </div>
                </br>
                <center>
                  <button class="btn btn-danger" type="submit">Submit</button>
                </center>
            </div>
          </div>

        </div>

      
      <h2>Recent Articles</h2>
      <div class="row">
        <div class="col-lg-3 col-sm-4 col-xs-6">
            <a href="#" class="thumbnail">
              <img src="http://lorempixel.com/150/150/sports/8" class="img-responsive">
            </a>
          </div>
        <div class="col-lg-3 col-sm-4 col-xs-6">
          <a href="#" class="thumbnail">
            <img src="http://lorempixel.com/150/150/sports/7" class="img-responsive">
          </a>
        </div>
        <div class="col-lg-3 col-sm-4 col-xs-6">
          <a href="#" class="thumbnail">
            <img src="http://lorempixel.com/150/150/sports/6" class="img-responsive">
          </a>
        </div>
        <div class="col-lg-3 col-sm-4 col-xs-6">
          <a href="#" class="thumbnail">
            <img src="http://lorempixel.com/150/150/sports/1" class="img-responsive">
          </a>
        </div>
      </div>

        <h2>Popular articles</h2>
        <div class="row">
          <div class="col-lg-3 col-sm-4 col-xs-6">
            <a href="#" class="thumbnail">
              <img src="http://lorempixel.com/150/150/sports/2" class="img-responsive">
            </a>
          </div>
        <div class="col-lg-3 col-sm-4 col-xs-6">
          <a href="#" class="thumbnail">
            <img src="http://lorempixel.com/150/150/sports/3" class="img-responsive">
          </a>
        </div>
        <div class="col-lg-3 col-sm-4 col-xs-6">
          <a href="#" class="thumbnail">
            <img src="http://lorempixel.com/150/150/sports/4" class="img-responsive">
          </a>
        </div>
        <div class="col-lg-3 col-sm-4 col-xs-6">
          <a href="#" class="thumbnail">
            <img src="http://lorempixel.com/150/150/sports/5" class="img-responsive">
          </a>
        </div> 
       </div>

app/views/posts/new.html.erb
<%= form_for @post, :html => {:multipart => true} do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div id="new-article">
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
  <br>
    <h5>Upload Image</h5>
    <%= f.file_field :image %>
  </p>
  <br>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/posts/show.html.erb
<div class = "row">
  <div class = "col-md-1">
    </div>
      <div class = "col-md-10">
        <center><h2><%= @post.title %></h2></a>
          <img src="http://lorempixel.com/200/260/sports/8" id = "article-image-show" class="img-responsive">
             <p><%= @post.text %></a></p>
      </div>

<div class = "col-md-1">
</div>

<div class = "row">
  <div class = "col-md-12">
          <div class="detailBox">
      <br>
     <div class="actionBox">
      <h3>Comments</h3>
        <ul class="commentList">
            <li>
                <div class="commenterImage">
                  <img src="http://lorempixel.com/50/50/people/6" />
                </div>
                <div class="commentText">
                    <p class="">Hello this is a test comment.</p> <span class="date sub-text">on March 5th, 2014</span>

                </div>
            </li>
            <li>
                <div class="commenterImage">
                  <img src="http://lorempixel.com/50/50/people/7" />
                </div>
                <div class="commentText">
                    <p class="">Hello this is a test comment and this comment is particularly very long and it goes on and on and on.</p> <span class="date sub-text">on March 5th, 2014</span>

                </div>
            </li>
            <li>
                <div class="commenterImage">
                  <img src="http://lorempixel.com/50/50/people/9" />
                </div>
                <div class="commentText">
                    <p class="">Hello this is a test comment.</p> <span class="date sub-text">on March 5th, 2014</span>

                </div>
            </li>
        </ul>
        <form class="form-inline" role="form">
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Leave a comment


                " />
            </div>
            <div class="form-group">
                <button class="btn btn-default">Add</button>
            </div>
        </form>
    </div>
</div>
          </div>
        </div>
          </div>

app/views/shared/_footer.html.erb
<div class = "footer">
  <div class = "container">

        <center>
          <div class = "row">
            <div class = "col-md-3">
                <h4>Join our Email List</h4>
                <p>Join my email list for weekly tips and free offers</p>
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                  <input type="text" class="form-control" placeholder="Enter email here">
                </div>
                </br>
                <center>
                  <button class="btn btn-danger" type="submit">Submit</button>
                </center>

            </div>
            <div class = "col-md-3">
                <h4>About Me</h4>
                  <p>Some shit about me and how aweseome I am</p>
            </div>
            <div class = "col-md-3">
                <h4>Contact</h4>
                  <p>Join my email list for weekly tips and free offers</p>
            </div>
            <div class = "col-md-3">
                <h4>Social</h4>
                    <a class="btn btn-social-icon btn-twitter">
                      <i class="fa fa-twitter fa-2x"></i>
                    </a>
                    <a class="btn btn-social-icon btn-twitter">
                      <i class="fa fa-facebook fa-2x"></i>
                    </a>
                    <a class="btn btn-social-icon btn-twitter">
                      <i class="fa fa-google-plus fa-2x"></i>
                    </a>
                    <a class="btn btn-social-icon btn-twitter">
                      <i class="fa fa-youtube fa-2x"></i>
                    </a>
            </div>
          </div>
        </center>
      </div>
    </div>
  </div>

app/views/shared/_header.html.erb
<nav class = "navbar navbar-inverse navbar-fixed-top" id = "header">
        <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="index.html" class="navbar-brand"><strong>Single Digit Success</strong></a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <form class="navbar-form navbar-right" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav">
                <li class="active"><%= link_to "Home", root_path %></li>
                <li><a href="posts.index.html">Articles and Videos</a></li>
                <li><a href="#">About</a></li>
                <% if current_user %>
                 <li><a>Logged in as <%= current_user.email %></a></li>
                 <li><%= link_to "Log out", log_out_path %></li>
               <% else %>
                 <li><%= link_to "Sign up", new_user_path %></li>
                 <li><%= link_to "Log in", log_in_path %></li>
               <% end %>
                
            </ul>
        </nav>
    </div>
    </nav>

app/views/users/new.html.erb
<div class = "container">
  <center>
  <h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>
</center>
</div>